### PR TITLE
New Features, some fixes and testing, testing, testing...

### PR DESCRIPTION
**Pull request by GastonZalba**
**Bugs**
- Fixed bug that happened when exporting in GeoJSON with the rawMetadata option enabled. Properties were always exported in 'string' type, including coordinates, so the file could not be properly imported in some programs.
- Fixed minor bug that discarded SRT fields when were present negative values (V.S and H.S. properties on P4RTK, for example)

**New features**
- It's now allowed to import an array of files (and fileNames). Each one is treated as a different feature/LineString within a single GeometryCollection. If a single dataString is passed, everything stays the same.
- CSV export was adapted/rewrited to export and merge mutiple files that may have different properties/columns.
- Added function to set custom properties to the CSV and GeoJSON.
- Added the property "NAME" (containing the fileName) in the CSV and GeoJSON formats, important to identify each file.

**Testings**
- Added several tests, with different formats and configurations.

### CODE REVIEW

**Comment by JuanIrache** [comment]
Hey, this is fantastic. Thanks!

Pitty that my initial code organization is not great (it was my first package), so updating it, reviewing changes, etc., is not super straightforward.

**Comment by JuanIrache** [comment]
Two issues I realised later. CircleCI integration breaks if the test command watches. I split the tests in two like so:

```
  "scripts": {
    "test-watch": "jest --watch",
    "test": "jest"
  },
```

Testing modifies the processed files, causing a ton of changes in git. Do you know why this is happening?

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   samples/processed_files/mavic_pro_CustomProperties.csv
        modified:   samples/processed_files/multi_mavic_pro_p4_rtk.csv
        modified:   samples/processed_files/multi_mavic_pro_p4_rtk.json
        modified:   samples/processed_files/multi_mavic_pro_p4_rtk.mgjson
        modified:   samples/processed_files/multi_mavic_pro_p4_rtk_MillisecondsPerSample(7000).json
        modified:   samples/processed_files/multi_mavic_pro_p4_rtk_Smoothing(0).json
        modified:   samples/processed_files/p4_rtk2.csv
        modified:   samples/processed_files/p4_rtk2.json
        modified:   samples/processed_files/p4_rtk2.mgjson
```

**Comment by GastonZalba** [comment]
I found [this](https://stackoverflow.com/questions/5787937/git-status-shows-files-as-changed-even-though-contents-are-the-same).  Probably the new tests are adding LF (Unix) newlines to the files, and the existing ones are CRLF (windows). Maybe it's better add that folder to .gitignore?

**Comment by JuanIrache** [comment]
Yes.

Also, those files are not necessary for the automated test to succeed, are they? I'm assuming they are reviewed manually. Maybe we could have a separate script that creates them for manual review?

**Comment by GastonZalba** [comment]
Yes, they are for manual review. They have a condition that evaluate is there are errors upon writing but it can be skipped (the "real" tests are before that). Tomorrow i can fix this with the extra script.

**Pull request merged**
